import "../../styles/dashboard.scss"

const Dashboard = () => {
  return (
    <div className="dashboard">
      <h2>Body Content</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod mi at urna vestibulum, eget interdum arcu pellentesque. Donec vitae orci justo. Mauris malesuada enim a dolor pretium, eget pharetra nisi hendrerit. Sed vel elit elit. Sed lacinia sodales felis in lacinia. Nullam malesuada neque id efficitur consequat. Nam fermentum, quam vel euismod accumsan, tortor purus placerat ex, vel malesuada purus metus eu velit. </p>
      </div>
  )
}

export default Dashboard